/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsHostIdRouteImport } from './routes/hosts.$hostId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedMyTicketsRouteImport } from './routes/_authenticated/my-tickets'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as AuthenticatedBecomeHostRouteImport } from './routes/_authenticated/become-host'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets.$ticketId'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedEventsEventIdCheckInRouteImport } from './routes/_authenticated/events.$eventId.check-in'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyTicketsRoute = AuthenticatedMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeHostRoute = AuthenticatedBecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsEventIdCheckInRoute =
  AuthenticatedEventsEventIdCheckInRouteImport.update({
    id: '/events/$eventId/check-in',
    path: '/events/$eventId/check-in',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/account': typeof AuthenticatedAccountRoute
  '/become-host': typeof AuthenticatedBecomeHostRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/account': typeof AuthenticatedAccountRoute
  '/become-host': typeof AuthenticatedBecomeHostRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/become-host': typeof AuthenticatedBecomeHostRoute
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/_authenticated/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/account'
    | '/become-host'
    | '/my-events'
    | '/my-tickets'
    | '/events/$eventId'
    | '/hosts/$hostId'
    | '/events/new'
    | '/tickets/$ticketId'
    | '/events/$eventId/check-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/account'
    | '/become-host'
    | '/my-events'
    | '/my-tickets'
    | '/events/$eventId'
    | '/hosts/$hostId'
    | '/events/new'
    | '/tickets/$ticketId'
    | '/events/$eventId/check-in'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/_authenticated/account'
    | '/_authenticated/become-host'
    | '/_authenticated/my-events'
    | '/_authenticated/my-tickets'
    | '/events/$eventId'
    | '/hosts/$hostId'
    | '/_authenticated/events/new'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/events/$eventId/check-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HostsHostIdRoute: typeof HostsHostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-tickets': {
      id: '/_authenticated/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedMyTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-host': {
      id: '/_authenticated/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof AuthenticatedBecomeHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId/check-in': {
      id: '/_authenticated/events/$eventId/check-in'
      path: '/events/$eventId/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckInRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBecomeHostRoute: typeof AuthenticatedBecomeHostRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedMyTicketsRoute: typeof AuthenticatedMyTicketsRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedEventsEventIdCheckInRoute: typeof AuthenticatedEventsEventIdCheckInRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBecomeHostRoute: AuthenticatedBecomeHostRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedMyTicketsRoute: AuthenticatedMyTicketsRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedEventsEventIdCheckInRoute:
    AuthenticatedEventsEventIdCheckInRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HostsHostIdRoute: HostsHostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
